### ISSUE TITLE
import.meta cause error TS1470

### ISSUE THREAD

**Issue by raythurnevoid** [qmhc/vite-plugin-dts#174]
### Describe the bug

When `import.meta` is used in the source code, the error: `TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.` is showed in console nevertheless the output is only ES.

### Reproduction

https://github.com/raythurnevoid/vite-dts-import-meta-issue

### Steps to reproduce

```
npm i
npm run build
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 16.51 GB / 31.42 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^4.1.1 => 4.1.1
    vite-plugin-dts: ^1.7.3 => 1.7.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You should change the `module` option to `ESNext`:

```json
{
  "compilerOptions": {
    "module": "ESNext"
  }
}
```

**Comment by raythurnevoid** [comment]
> You should change the `module` option to `ESNext`:
> 
> ```json
> {
>   "compilerOptions": {
>     "module": "ESNext"
>   }
> }
> ```

Works with `ESNext`.
Still I'm not sure, but probably it shouldn't break with `NodeNext` either.
tsc is working fine with `NodeNext`: `tsc --declaration --emitDeclarationOnly --outDir dist`

**Comment by qmhc** [comment]
This issue seems to have been fixed in past updates, so close it now.

Might reopen if any update.
